apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
  namespace: prosimo-monitoring
data:
  beyla-config.yml: |
    # this is required to enable kubernetes discovery and metadata
    attributes:
      kubernetes:
        enable: true
    # this will provide automatic routes report while minimizing cardinality
    routes:
      unmatched: heuristic
    # let's instrument only the docs server
    discovery:
      services:
        - k8s_deployment_name: 
        - k8s_namespace: "default