apiVersion: v1
kind: Secret
metadata:
  namespace: beyla
  name: grafana-credentials
type: Opaque
stringData:
  tempo-endpoint: "tempo-<region>.grafana.net:443"
  tempo-user: "<tempo user>"
  mimir-endpoint: "prometheus-<region>.grafana.net"
  mimir-user: "<mimir user>"
  grafana-api-key: "<grafana api key>"
